domains:
  - ecommerce-backend
php_version: "8.5"
framework: laravel
framework_version: "12"
secured: true
services:
  - mailpit
  - meilisearch
  - postgres
  - redis
  - rustfs
workers:
  - queue
  - schedule
